# AMBARELLA Platform Support
snd-soc-ambarella-objs := ambarella_pcm.o
snd-soc-ambarella-i2s-objs := ambarella_i2s.o

obj-$(CONFIG_SND_AMBARELLA_SOC)		+= snd-soc-ambarella.o
obj-$(CONFIG_SND_AMBARELLA_SOC_I2S)	+= snd-soc-ambarella-i2s.o

# AMBARELLA Machine Support
snd-soc-ambevk-objs := ambevk.o
snd-soc-i1evk-objs := i1evk.o
snd-soc-dummy-objs := dummy.o
snd-soc-s2lmkiwi-objs := s2lmkiwi.o
snd-soc-ambcloudcam-objs := ambcloudcam.o
snd-soc-s2lrdb-objs := s2lrdb.o

obj-$(CONFIG_AMBEVK_BOARD)		+= snd-soc-ambevk.o
obj-$(CONFIG_I1EVK_BOARD)		+= snd-soc-i1evk.o
obj-$(CONFIG_AMBARELLA_DUMMY_BOARD)	+= snd-soc-dummy.o
obj-$(CONFIG_S2LMKIWI_BOARD)		+= snd-soc-s2lmkiwi.o
obj-$(CONFIG_STRAWBERRY_BOARD)		+= snd-soc-ambcloudcam.o
obj-$(CONFIG_S2LRDB_BOARD)		+= snd-soc-s2lrdb.o
